sources:
  # Saved Barchart API data
  barchart_saved:
    class: plugins.data_sources.saved_data.SavedDataSource
    config:
      file_path: "data/api_responses/options_data_20250602_141553.json"
  
  # Alternative saved data locations
  latest_saved:
    class: plugins.data_sources.saved_data.SavedDataSource
    config:
      file_path: "data/normalized/latest_options_data.json"
  
  # Future data sources can be added here:
  # 
  # barchart_live:
  #   class: plugins.data_sources.barchart_api.BarchartAPI
  #   config:
  #     endpoint: "https://www.barchart.com/proxies/core-api/v1/quotes/get"
  #     symbol: "MC6M25"
  # 
  # tradovate:
  #   class: plugins.data_sources.tradovate_api.TradovateAPI
  #   config:
  #     cid: "6540"
  #     secret: "f7a2b8f5-8348-424f-8ffa-047ab7502b7c"
  #     demo: true
  # 
  # csv_file:
  #   class: plugins.data_sources.csv_file.CSVDataSource
  #   config:
  #     file_path: "data/raw/options_data.csv"
  #     date_format: "%Y-%m-%d"