strategies:
  # Expected Value Strategy (current algorithm)
  expected_value:
    class: plugins.strategies.expected_value.ExpectedValueStrategy
    config:
      weights:
        oi_factor: 0.35      # Open Interest weight (35%)
        vol_factor: 0.25     # Volume weight (25%)
        pcr_factor: 0.25     # Put/Call Ratio weight (25%)
        distance_factor: 0.15 # Distance weight (15%)
      min_ev: 15             # Minimum Expected Value
      min_probability: 0.60  # Minimum probability (60%)
      max_risk: 150          # Maximum risk in points
      min_risk_reward: 1.0   # Minimum risk/reward ratio
  
  # Conservative EV settings
  expected_value_conservative:
    class: plugins.strategies.expected_value.ExpectedValueStrategy
    config:
      weights:
        oi_factor: 0.40      # Higher weight on Open Interest
        vol_factor: 0.30     # Higher weight on Volume
        pcr_factor: 0.20     # Lower weight on PCR
        distance_factor: 0.10 # Lower weight on Distance
      min_ev: 25             # Higher minimum EV
      min_probability: 0.70  # Higher probability requirement
      max_risk: 100          # Lower max risk
      min_risk_reward: 1.5   # Higher risk/reward requirement
  
  # Aggressive EV settings
  expected_value_aggressive:
    class: plugins.strategies.expected_value.ExpectedValueStrategy
    config:
      weights:
        oi_factor: 0.30      # Lower weight on Open Interest
        vol_factor: 0.20     # Lower weight on Volume
        pcr_factor: 0.30     # Higher weight on PCR (momentum)
        distance_factor: 0.20 # Higher weight on Distance
      min_ev: 10             # Lower minimum EV
      min_probability: 0.55  # Lower probability requirement
      max_risk: 200          # Higher max risk
      min_risk_reward: 0.8   # Lower risk/reward requirement

# Future strategies can be added here:
#
# momentum_analysis:
#   class: plugins.strategies.momentum_analysis.MomentumStrategy
#   config:
#     lookback_period: 20
#     momentum_threshold: 0.1
#     volume_threshold: 1000
#
# volatility_analysis:
#   class: plugins.strategies.volatility_analysis.VolatilityStrategy
#   config:
#     window_size: 14
#     volatility_threshold: 0.25
#     include_iv_rank: true
#
# gamma_exposure:
#   class: plugins.strategies.gamma_exposure.GammaExposureStrategy
#   config:
#     strike_range: 0.05
#     time_decay_factor: 0.8
#     hedge_ratio_threshold: 0.1
#
# flow_analysis:
#   class: plugins.strategies.flow_analysis.FlowAnalysisStrategy
#   config:
#     unusual_volume_threshold: 2.0  # 2x average volume
#     large_trade_threshold: 100     # Contracts
#     time_window_minutes: 30